baseURL = "https://www.agate-pris.dev/"
languageCode = "ja-jp"
title = "agate-pris.dev"
theme = "hugo-coder"

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Agate Pris"
avatarURL = "images/8687_FTIN2Ms0.png"
colorScheme = "auto"
hideColorSchemeToggle = true
customCSS = ["css/custom.css", "css/fontcustom.css"]
dateFormat = "2006-01-02"
since = 2019

[params.utterances]
repo = "agate-pris/comments.agate-pris.dev"
issueTerm = "pathname"
theme = "preferred-color-scheme"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
url = "https://twitter.com/agate_pris"

[[params.social]]
name = "Moments / Twitter"
icon = "fa fa-2x icon-twitter-moments"
url = "https://twitter.com/agate_pris/moments"

[[params.social]]
name = "Twitch"
icon = "fa fa-2x fa-twitch"
url = "https://www.twitch.tv/agate_pris"

[[params.social]]
name = "GitHub"
icon = "fa fa-2x fa-github"
url = "https://github.com/agate-pris"

[[params.social]]
name = "GitLab"
icon = "fa fa-2x fa-gitlab"
url = "https://gitlab.com/agate-pris"

[[params.social]]
name = "Qiita"
icon = "fa fa-2x icon-qiita"
url = "https://qiita.com/agate-pris"

[[params.social]]
name = "note"
icon = "fa fa-2x icon-note-com"
url = "https://note.com/agate_pris"

[[params.social]]
name = "Hatena Blog"
icon = "fa fa-2x icon-hatenablog"
url = "https://altebute.hatenablog.com/"

[[params.social]]
name = "Blogger"
icon = "fa fa-2x icon-blogger"
url = "https://altebute.blogspot.com/"

[[params.social]]
name = "DeviantArt"
icon = "fa fa-2x fa-deviantart"
url = "https://www.deviantart.com/agate-pris"

[[params.social]]
name = "Amazon Wishlist"
icon = "fa fa-2x fa-amazon"
url = "https://www.amazon.jp/hz/wishlist/ls/MNV541VIJ66S?ref_=wl_share"

[[params.social]]
name = "Pinterest"
icon = "fa fa-2x fa-pinterest"
url = "https://pinterest.jp/agatepris"

[[menu.main]]
name = "Profile"
weight = 1
url = "profile/"

[[menu.main]]
name = "Works"
weight = 2
url = "works/"

[[menu.main]]
name = "Posts"
weight = 3
url = "posts/"

[[menu.main]]
name = "About my Avatar"
weight = 4
url = "avatar/"
