baseURL = "http://agate-pris.dev/"
languageCode = "ja-jp"
title = "agate-pris.dev"
theme = "hugo-coder"

[markup.goldmark.renderer]
    unsafe= true

[params]
    dateform = "2006-01-02"

[[menu.main]]
    name = "Posts"
    weight = 1
    url = "posts/"

[[menu.main]]
    name = "Profile"
    weight = "1"
    url = "profile/"

[[menu.main]]
    name = "Twitter"
    weight = "1"
    url = "https://twitter.com/agate_pris"
